### ISSUE TITLE
RS232 through Cordovarduino

### ISSUE THREAD

**Issue by mbrasile** [xseignard/cordovarduino#29]
I see Cordovarduino rely on serial communications, but it adds the usb manager to let it work with usb virtual serial ports only.  Is that possible to use in some way the plugin to drive native serial RS232 ports?

Thank you in advance.

**Comment by xseignard** [comment]
Hello,

As stated in #9 by @ndvalkov, it should work with @hendrikmaus #6 

Regards

**Comment by mbrasile** [comment]
thanks a lot for this feedback; so it seems I can send raw data to a serial channel.

but as I have written, my problem is the serial port I have is native (/dev/ttyS0) so I have no udb-adaptor and the initial detection of the plugin find no devices. how can I handle this?

**Comment by xseignard** [comment]
the plugin, as it is written, only supports usb serial driver based.

I think it would be possible to update the plugin to handle such case.

Best thing to do is to submit an issue here mik3y/usb-serial-for-android, since this cordova plugin relies on this java lib.

With some answers from them and your help for testing it on the cordova plugin, we should be able to do it.

Regards,

Xavier

**Comment by mbrasile** [comment]
thanks again, I've just added an issue on <a href="https://github.com/mik3y/usb-serial-for-android/issues/105">usb-serial-for-android</a>.
