### ISSUE TITLE
How to get it running?

### ISSUE THREAD

**Issue by MrGlasspoole** [xseignard/cordovarduino#50]
I'm trying to run a FTDI or CP21xx on my Android device.
I added:
```
serial.requestPermission(
  function success() {
    window.alert("Success msg!!!");
  },
  function error() {
    window.alert("error msg");
  }
);
```
to my JS. But nothing happens. Shouldn't there at least the error message pop up?
Then there is also a link to https://github.com/mik3y/usb-serial-for-android - do i need to add this? 
Also the vid and pid is something that is confusing. I checked it with the "USB Device Info" app and get every time another pid for the same device.
If i try lsusb i have every time the same vid/pid no matter if i connect the FTDI or CP21xx.

Please somebody tell me the steps how to get this running. 
I need to say I'm new to Cordova and maybe i miss something that everybody knows but me.

**Comment by xseignard** [comment]
Hello,
Here is a sample project: https://github.com/xseignard/demoCordovarduino

Could you try it and see if it work for you?

**Comment by MrGlasspoole** [comment]
I will check it.
But why do i not get a fixed vid/pid.
Why does lsusb only show one vid/pid no matter what is connected?
To me it seems like the FTDI or CP21xx are not recognized...

**Comment by PaulBeaudet** [comment]
I didn't realize android studio had wifi debugging sounds scary and super neat at the same time.

> There is another thing that i find complicated:
>   Do you upload Cordova through USB and always switch the cable between PC and the USB/TTL?
>   Thats not practical for testing if you need to do it after every bit of code change.

Yes that what I've been doing, whether it's practical or not is up to you. For me Android studio is super bloated and chatty, takes forever just to load up. Might not be faster in my case. Sans wifi I would have to plug and unplug my robot anyhow, it's not much of a loss. That's just me though, I have more problems with MPT getting in the way of USB debugging, and cordova continuously trying to run my code on the useless emulator. (good luck emulating the arduino cordova... haha)

I don't think I can really help with your connection issue because I'm not sure what you are trying to do, but just out of curiosity what Arduino are you trying to use? You said FTDI and CP21XX which are basically usb to serial bridges at the end of the day right? Your probably going to have to look lower level in the code to see if they are compatible. I haven't had any issues with the Uno and the default options, but I do have other arduinos I could test no FTDI chips though

**Comment by xseignard** [comment]
@MrGlasspoole changing VID/PID is not normal. Try to plug your device on your computer and run `lsusb` to check VID/PID.

You can run `adb` over wifi, please chec http://stackoverflow.com/questions/2604727/how-can-i-connect-to-android-with-adb-over-tcp

FTDI and CP21XX should be supported. Please give more info about your setup, devices and so on.

**Comment by xseignard** [comment]
Any updates?

**Comment by xseignard** [comment]
No updates, I close the issue.
Feel free to reopen it if needed.
